DELETE FROM automation_bot.trigger_added_events;
DELETE FROM automation_bot.trigger_removed_events;
DELETE FROM automation_bot.approval_granted_events;
DELETE FROM automation_bot.approval_removed_events;
DELETE FROM automation_bot.trigger_executed_events;