on:
    push:
      branches:
        - dev
  
name: Deploy to AWS Staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    env:
      AWS_REGION: eu-central-1
      ECR_REPO_NAME: cache-staging
      GOERLI_ETL_SERVICE_NAME: cache-etl-goerli-staging
      GOERLI_API_SERVICE_NAME: cache-api-goerli-staging
      MAINNET_ETL_SERVICE_NAME: cache-etl-mainnet-staging
      MAINNET_API_SERVICE_NAME: cache-api-mainnet-staging
      CLUSTER_NAME: cache-staging

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: ${{ secrets.BUILD_DEPLOY_OIDC_ROLE_STAGING }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract commit hash
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        SHA_TAG: ${{ steps.vars.outputs.sha_short }}
        LATEST_TAG: latest
        ENVIRONMENT_TAG: staging
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$SHA_TAG \
                     -t $ECR_REGISTRY/$ECR_REPO_NAME:$LATEST_TAG \
                     -t $ECR_REGISTRY/$ECR_REPO_NAME:$ENVIRONMENT_TAG \
                     .
        docker push $ECR_REGISTRY/$ECR_REPO_NAME --all-tags

    - name: Update Goerli ETL ECS service with latest Docker image
      id: service-update-goerli-etl
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME  --service ${{ env.GOERLI_ETL_SERVICE_NAME }} --force-new-deployment --region $AWS_REGION

    - name: Update Goerli API ECS service with latest Docker image
      id: service-update-goerli-api
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME  --service ${{ env.GOERLI_API_SERVICE_NAME }} --force-new-deployment --region $AWS_REGION

    - name: Update Mainnet ETL ECS service with latest Docker image
      id: service-update-mainnet-etl
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME  --service ${{ env.MAINNET_ETL_SERVICE_NAME }} --force-new-deployment --region $AWS_REGION

    - name: Update Mainnet API ECS service with latest Docker image
      id: service-update-mainnet-api
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME  --service ${{ env.MAINNET_API_SERVICE_NAME }} --force-new-deployment --region $AWS_REGION
