on:
    push:
      branches:
        - aws-prod
  
name: Deploy to AWS Production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      AWS_REGION: us-east-1
      ECR_REPO_NAME: cache-prod
      ETL_SERVICE_NAME: cache-etl-mainnet-prod
      API_SERVICE_NAME: cache-api-mainnet-prod
      CLUSTER_NAME: cache-prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: ${{ secrets.BUILD_DEPLOY_OIDC_ROLE_PROD }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract commit hash
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        SHA_TAG: ${{ steps.vars.outputs.sha_short }}
        LATEST_TAG: latest
        ENVIRONMENT_TAG: prod
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$SHA_TAG \
                     -t $ECR_REGISTRY/$ECR_REPO_NAME:$LATEST_TAG \
                     -t $ECR_REGISTRY/$ECR_REPO_NAME:$ENVIRONMENT_TAG \
                     .
        docker push $ECR_REGISTRY/$ECR_REPO_NAME --all-tags

    - name: Update Mainnet ETL ECS service with latest Docker image
      id: service-update-etl
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME  --service ${{ env.ETL_SERVICE_NAME }} --force-new-deployment --region $AWS_REGION

    - name: Update Mainnet API ECS service with latest Docker image
      id: service-update-api
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME  --service ${{ env.API_SERVICE_NAME }} --force-new-deployment --region $AWS_REGION

